# Generated by Django 2.2.7 on 2019-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_retirada', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('roupa', models.ForeignKey(on_delete='CASCADE', to='cadastro.Roupa')),
            ],
        ),
    ]
