# Generated by Django 2.2.7 on 2019-11-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_aluguel_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete='CASCADE', to='cadastro.Cliente'),
        ),
    ]
