# Generated by Django 2.2.7 on 2019-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_taxas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='taxa',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='financeiro.Taxas'),
        ),
    ]
