# Generated by Django 2.2.7 on 2019-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=16)),
                ('nada', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=16)),
                ('dia_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaRoupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRoupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_roupa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_roupa', models.CharField(max_length=50)),
                ('qtd_estoque', models.IntegerField(default=0)),
                ('disponivel', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete='CASCADE', to='cadastro.MarcaRoupa')),
                ('sessao', models.ForeignKey(on_delete='CASCADE', to='cadastro.Sessao')),
                ('tipo_roupa', models.ForeignKey(on_delete='CASCADE', to='cadastro.TipoRoupa')),
            ],
        ),
    ]
