# Generated by Django 2.2.7 on 2019-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_roupa_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='img_roupa',
            field=models.ImageField(blank=True, height_field=10, null=True, upload_to='', width_field=10),
        ),
    ]
