# Generated by Django 2.2.7 on 2019-11-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_roupa_img_roupa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='login',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
    ]
