# Generated by Django 2.2.7 on 2019-11-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20191125_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roupa',
            name='img_roupa',
        ),
    ]
